<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="85990" started-at="2018-09-18T10:46:04Z" finished-at="2018-09-18T10:47:30Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="85990" started-at="2018-09-18T10:46:04Z" finished-at="2018-09-18T10:47:30Z">
      <class name="facebook.testCases.LoginTest">
        <test-method status="PASS" signature="doLogin(java.util.Hashtable)[pri:0, instance:facebook.testCases.LoginTest@6be70a]" name="doLogin" duration-ms="41972" started-at="2018-09-18T16:16:05Z" data-provider="giveData" finished-at="2018-09-18T16:16:47Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=computer8, browser=mozilla, userName=mallimurthy2@gmail.com, runmode=y, expectedResult=success}]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:facebook.testCases.LoginTest@6be70a]" name="quit" is-config="true" duration-ms="634" started-at="2018-09-18T16:16:47Z" finished-at="2018-09-18T16:16:48Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
        <test-method status="FAIL" signature="doLogin(java.util.Hashtable)[pri:0, instance:facebook.testCases.LoginTest@6be70a]" name="doLogin" duration-ms="42475" started-at="2018-09-18T16:16:48Z" data-provider="giveData" finished-at="2018-09-18T16:17:30Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[{password=some, browser=chrome, userName=some@gmail.com, runmode=y, expectedResult=success}]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: test failed
	at org.testng.Assert.fail(Assert.java:94)
	at base.BaseTest.reportFailure(BaseTest.java:81)
	at facebook.testCases.LoginTest.doLogin(LoginTest.java:54)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="quit()[pri:0, instance:facebook.testCases.LoginTest@6be70a]" name="quit" is-config="true" duration-ms="68" started-at="2018-09-18T16:17:30Z" finished-at="2018-09-18T16:17:30Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- quit -->
      </class> <!-- facebook.testCases.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
